sonarr:
  image:
    repository: tccr.io/truecharts/overseerr
    tag: 1.32.5@sha256:8756b1d3d2fa8fde07e84e686cf7cb2cb99e7c741bfc82c62735c19354734db0
    pullPolicy: IfNotPresent

  securityContext:
    readOnlyRootFilesystem: false

  env:
    LOG_LEVEL: info

  service:
    main:
      ports:
        main:
          port: 5055
          targetPort: 5055

  ingress:
    # -- Enable and configure ingress settings for the chart under this key.
    # @default -- See values.yaml
    main:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: overseerr.svc.cluster.local
          paths:
            - path: /
              # Ignored if not kubeVersion >= 1.14-0
              pathType: Prefix
  persistence:
    config:
      enabled: true
      mountPath: "/app/config"

  portal:
    enabled: true
