apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: Default Project

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'

  destinations:
  - namespace: 'argocd'
    server: {{ .server | default "https://kubernetes.default.svc" | quote }}

  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  roles:
  # A role which provides read-only access to all applications in the project
  - name: read-only
    description: Read-only privileges to default
    policies:
    - p, role:read-only, *, get, *, allow
    - p, role:read-oefault, *, list, *, allow

  # A role which provides sync privileges to only the guestbook-dev application
  - name: argocd
    description: Sync privileges for all apps in all namespaces
    policies:
    - p, role:argocd, *, applications *, allow