{
 "title": "Single Node focus",
 "tags": [ "linux" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   { "name": "diskdevices", "query": "[a-z]+|nvme[0-9]+n[0-9]+" },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "resolution",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Quick CPU / Mem / Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Busy",
     "type": "gauge",
     "description": "Busy state of all CPU cores together",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(((count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=\"$node\",job=\"$job\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))"
      }
     ]
    },
    {
     "title": "Sys Load (5m avg)",
     "type": "gauge",
     "description": "Busy state of all CPU cores together (5 min average)",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_load5{instance=\"$node\",job=\"$job\"}) /  count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)) * 100"
      }
     ]
    },
    {
     "title": "Sys Load (15m avg)",
     "type": "gauge",
     "description": "Busy state of all CPU cores together (15 min average)",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_load15{instance=\"$node\",job=\"$job\"}) /  count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)) * 100"
      }
     ]
    },
    {
     "title": "RAM Used",
     "type": "gauge",
     "description": "Non available RAM memory",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$node\",job=\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"})"
      }
     ]
    },
    {
     "title": "SWAP Used",
     "type": "gauge",
     "description": "Used Swap",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"}) / (node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} )) * 100"
      }
     ]
    },
    {
     "title": "Root FS Used",
     "type": "gauge",
     "description": "Used Root FS",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})"
      }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "stat",
     "description": "Total number of CPU cores",
     "gridPos": { "h": 2, "w": 2, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "description": "System uptime",
     "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_time_seconds{instance=\"$node\",job=\"$job\"} - node_boot_time_seconds{instance=\"$node\",job=\"$job\"}"
      }
     ]
    },
    {
     "title": "RootFS Total",
     "type": "stat",
     "description": "Total RootFS",
     "gridPos": { "h": 2, "w": 2, "x": 18, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}"
      }
     ]
    },
    {
     "title": "RAM Total",
     "type": "stat",
     "description": "Total RAM",
     "gridPos": { "h": 2, "w": 2, "x": 20, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}"
      }
     ]
    },
    {
     "title": "SWAP Total",
     "type": "stat",
     "description": "Total SWAP",
     "gridPos": { "h": 2, "w": 2, "x": 22, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"}"
      }
     ]
    }
   ]
  },
  { "title": "CPU / Memory / Net / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "nvidia_smi_memory_used_bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(nvidia_smi_memory_used_bytes) by  (app_kubernetes_io_instance, instance)"
    }
   ]
  },
  {
   "title": "nvidia_smi_utilization_gpu_ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(nvidia_smi_utilization_gpu_ratio) by  (app_kubernetes_io_instance, instance)"
    }
   ]
  },
  {
   "title": "nvidia_smi_power_draw_watts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
   "targets": [
    {
     "expr": "sum(nvidia_smi_power_draw_watts) by  (app_kubernetes_io_instance, instance)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "percentage" }
   ],
   "targets": [
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode=\"system\",instance=\"$node\",job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "System - Processes executing in kernel mode"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='user',instance=\"$node\",job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "User - Normal processes executing in user mode"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='nice',instance=\"$node\",job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Nice - Niced processes executing in user mode"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=\"$node\",job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Idle - Waiting for something to happen"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='iowait',instance=\"$node\",job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Iowait - Waiting for I/O to complete"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='irq',instance=\"$node\",job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Irq - Servicing interrupts"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='softirq',instance=\"$node\",job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Softirq - Servicing softirqs"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='steal',instance=\"$node\",job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='guest',instance=\"$node\",job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Guest - Time spent running a virtual CPU for a guest operating system"
    }
   ]
  },
  {
   "title": "I/O Usage Read / Write",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])) by (instance,device)",
     "legendFormat": "{{instance}} {{device}} - read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])) by (instance,device)",
     "legendFormat": "{{instance}} {{device}} - written"
    }
   ]
  },
  {
   "title": "Disk IOps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_reads_completed_total{job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])) by (instance, device)",
     "legendFormat": "{{{instance}}  {{device}} - Reads completed"
    },
    {
     "expr": "sum(rate(node_disk_writes_completed_total{instanjob=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])) by (instance, device)",
     "legendFormat": "{{{instance}} {device}} - Writes completed"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"} - (node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "I/O Utilization",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_io_time_seconds_total{job=\"$job\",device=~\"$diskdevices\"} [$__rate_interval])) by(instance,device)",
     "legendFormat": "{{instance}} {{device}}"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  { "title": "Storage Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Disk IOps Completed",
   "type": "graph",
   "description": "The number (after merges) of I/O requests completed per second for the device",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Reads completed"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Writes completed"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "graph",
   "description": "The number of bytes read from or written to the device per second",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "Bps", "label": "bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Read bytes"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Written bytes"
    }
   ]
  },
  {
   "title": "Disk Average Wait Time",
   "type": "graph",
   "description": "The average time for requests issued to the device to be served. This includes the time spent by the requests in queue and the time spent servicing them.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "s", "label": "time. read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval]) / rate(node_disk_reads_completed_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Read wait time avg"
    },
    {
     "expr": "rate(node_disk_write_time_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval]) / rate(node_disk_writes_completed_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Write wait time avg"
    }
   ]
  },
  {
   "title": "Average Queue Size",
   "type": "graph",
   "description": "The average queue length of the requests that were issued to the device",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "none", "label": "aqu-sz" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_weighted_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk R/W Merged",
   "type": "graph",
   "description": "The number of read and write requests merged per second that were queued to the device",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "iops", "label": "I/Os" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_merged_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Read merged"
    },
    {
     "expr": "rate(node_disk_writes_merged_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Write merged"
    }
   ]
  },
  {
   "title": "Time Spent Doing I/Os",
   "type": "graph",
   "description": "Percentage of elapsed time during which I/O requests were issued to the device (bandwidth utilization for the device). Device saturation occurs when this value is close to 100% for devices serving requests serially.  But for devices  serving requests in parallel, such as RAID arrays and modern SSDs, this number does not reflect their performance limits.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "percentunit", "label": "%util" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - IO"
    },
    {
     "expr": "rate(node_disk_discard_time_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - discard"
    }
   ]
  },
  {
   "title": "Instantaneous Queue Size",
   "type": "graph",
   "description": "The number of outstanding requests at the instant the sample was taken. Incremented as requests are given to appropriate struct request_queue and decremented as they finish.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "none", "label": "Outstanding req." }
   ],
   "targets": [
    {
     "expr": "node_disk_io_now{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{device}} - IO now"
    }
   ]
  },
  {
   "title": "Disk IOps Discards completed / merged",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "iops", "label": "IOs" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_discards_completed_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Discards completed"
    },
    {
     "expr": "rate(node_disk_discards_merged_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Discards merged"
    }
   ]
  },
  { "title": "Storage Filesystem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Filesystem space available",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}} - Available"
    }
   ]
  },
  {
   "title": "File Nodes Free",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "short", "label": "file nodes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_files_free{instance=\"$node\",job=\"$job\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}} - Free file nodes"
    }
   ]
  },
  {
   "title": "File Descriptor",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short", "label": "files" }
   ],
   "targets": [
    {
     "expr": "node_filefd_maximum{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Max open files"
    },
    {
     "expr": "node_filefd_allocated{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Open files"
    }
   ]
  },
  {
   "title": "File Nodes Size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short", "label": "file Nodes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_files{instance=\"$node\",job=\"$job\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}} - File nodes total"
    }
   ]
  },
  {
   "title": "Filesystem in ReadOnly / Error",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short", "label": "counter" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_readonly{instance=\"$node\",job=\"$job\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}} - ReadOnly"
    },
    {
     "expr": "node_filesystem_device_error{instance=\"$node\",job=\"$job\",device!~'rootfs',fstype!~'tmpfs'}",
     "legendFormat": "{{mountpoint}} - Device error"
    }
   ]
  },
  { "title": "Network Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "Network Traffic by Packets",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "pps", "label": "packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_packets_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "rate(node_network_transmit_packets_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Network Traffic Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 93 },
   "yaxes": [
    { "format": "pps", "label": "packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_errs_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Receive errors"
    },
    {
     "expr": "rate(node_network_transmit_errs_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Rransmit errors"
    }
   ]
  },
  {
   "title": "Network Traffic Drop",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "pps", "label": "packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_drop_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Receive drop"
    },
    {
     "expr": "rate(node_network_transmit_drop_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Transmit drop"
    }
   ]
  },
  {
   "title": "Network Traffic Compressed",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 103 },
   "yaxes": [
    { "format": "pps", "label": "packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_compressed_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Receive compressed"
    },
    {
     "expr": "rate(node_network_transmit_compressed_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Transmit compressed"
    }
   ]
  },
  {
   "title": "Network Traffic Multicast",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "pps", "label": "packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_multicast_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Receive multicast"
    }
   ]
  },
  {
   "title": "Network Traffic Fifo",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 113 },
   "yaxes": [
    { "format": "pps", "label": "packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_fifo_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Receive fifo"
    },
    {
     "expr": "rate(node_network_transmit_fifo_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Transmit fifo"
    }
   ]
  },
  {
   "title": "Network Traffic Frame",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 123 },
   "yaxes": [
    { "format": "pps", "label": "packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_frame_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Receive frame"
    }
   ]
  },
  {
   "title": "Network Traffic Carrier",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 123 },
   "yaxes": [
    { "format": "short", "label": "counter" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_carrier_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Statistic transmit_carrier"
    }
   ]
  },
  {
   "title": "Network Traffic Colls",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 133 },
   "yaxes": [
    { "format": "short", "label": "counter" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_colls_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Transmit colls"
    }
   ]
  },
  {
   "title": "NF Contrack",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 133 },
   "yaxes": [
    { "format": "short", "label": "entries" }
   ],
   "targets": [
    {
     "expr": "node_nf_conntrack_entries{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "NF conntrack entries"
    },
    {
     "expr": "node_nf_conntrack_entries_limit{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "NF conntrack limit"
    }
   ]
  },
  {
   "title": "ARP Entries",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 143 },
   "yaxes": [
    { "format": "short", "label": "Entries" }
   ],
   "targets": [
    {
     "expr": "node_arp_entries{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{ device }} - ARP entries"
    }
   ]
  },
  {
   "title": "MTU",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 143 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_network_mtu_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{ device }} - Bytes"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 153 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_network_speed_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{ device }} - Speed"
    }
   ]
  },
  {
   "title": "Queue Length",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 153 },
   "yaxes": [
    { "format": "none", "label": "packets" }
   ],
   "targets": [
    {
     "expr": "node_network_transmit_queue_length{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{ device }} -   Interface transmit queue length"
    }
   ]
  },
  {
   "title": "Softnet Packets",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 163 },
   "yaxes": [
    {
     "format": "short",
     "label": "packetes drop (-) / process (+)"
    }
   ],
   "targets": [
    {
     "expr": "rate(node_softnet_processed_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "CPU {{cpu}} - Processed"
    },
    {
     "expr": "rate(node_softnet_dropped_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "CPU {{cpu}} - Dropped"
    }
   ]
  },
  {
   "title": "Softnet Out of Quota",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 163 },
   "yaxes": [
    { "format": "short", "label": "counter" }
   ],
   "targets": [
    {
     "expr": "rate(node_softnet_times_squeezed_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "CPU {{cpu}} - Squeezed"
    }
   ]
  },
  {
   "title": "Network Operational Status",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 173 },
   "yaxes": [
    { "format": "short", "label": "counter" }
   ],
   "targets": [
    {
     "expr": "node_network_up{operstate=\"up\",instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{interface}} - Operational state UP"
    },
    {
     "expr": "node_network_carrier{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{device}} - Physical link state"
    }
   ]
  },
  { "title": "Network Sockstat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 183 } },
  {
   "title": "Sockstat TCP",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 184 },
   "yaxes": [
    { "format": "short", "label": "counter" }
   ],
   "targets": [
    {
     "expr": "node_sockstat_TCP_alloc{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "TCP_alloc - Allocated sockets"
    },
    {
     "expr": "node_sockstat_TCP_inuse{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "TCP_inuse - Tcp sockets currently in use"
    },
    {
     "expr": "node_sockstat_TCP_orphan{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "TCP_orphan - Orphan sockets"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "TCP_tw - Sockets wating close"
    }
   ]
  },
  {
   "title": "Sockstat UDP",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 184 },
   "yaxes": [
    { "format": "short", "label": "counter" }
   ],
   "targets": [
    {
     "expr": "node_sockstat_UDPLITE_inuse{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "UDPLITE_inuse - Udplite sockets currently in use"
    },
    {
     "expr": "node_sockstat_UDP_inuse{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "UDP_inuse - Udp sockets currently in use"
    },
    {
     "expr": "node_sockstat_UDP_mem{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "UDP_mem - Used memory for udp"
    }
   ]
  },
  {
   "title": "Sockstat FRAG / RAW",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 194 },
   "yaxes": [
    { "format": "short", "label": "counter" }
   ],
   "targets": [
    {
     "expr": "node_sockstat_FRAG_inuse{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "FRAG_inuse - Frag sockets currently in use"
    },
    {
     "expr": "node_sockstat_RAW_inuse{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAW_inuse - Raw sockets currently in use"
    }
   ]
  },
  {
   "title": "Sockstat Memory Size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 194 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_sockstat_TCP_mem_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "mem_bytes - TCP sockets in that state"
    },
    {
     "expr": "node_sockstat_UDP_mem_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "mem_bytes - UDP sockets in that state"
    },
    {
     "expr": "node_sockstat_FRAG_memory{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "FRAG_memory - Used memory for frag"
    }
   ]
  },
  {
   "title": "Sockstat Used",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 204 },
   "yaxes": [
    { "format": "short", "label": "sockets" }
   ],
   "targets": [
    {
     "expr": "node_sockstat_sockets_used{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Sockets_used - Sockets currently in use"
    }
   ]
  },
  { "title": "Network Netstat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 214 } },
  {
   "title": "Netstat IP In / Out Octets",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 215 },
   "yaxes": [
    { "format": "short", "label": "octects out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_netstat_IpExt_InOctets{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "InOctets - Received octets"
    },
    {
     "expr": "rate(node_netstat_IpExt_OutOctets{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "OutOctets - Sent octets"
    }
   ]
  },
  {
   "title": "Netstat IP Forwarding",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 215 },
   "yaxes": [
    { "format": "short", "label": "datagrams" }
   ],
   "targets": [
    {
     "expr": "rate(node_netstat_Ip_Forwarding{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Forwarding - IP forwarding"
    }
   ]
  },
  {
   "title": "ICMP In / Out",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 225 },
   "yaxes": [
    { "format": "short", "label": "messages out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_netstat_Icmp_InMsgs{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "InMsgs -  Messages which the entity received. Note that this counter includes all those counted by icmpInErrors"
    },
    {
     "expr": "rate(node_netstat_Icmp_OutMsgs{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "OutMsgs - Messages which this entity attempted to send. Note that this counter includes all those counted by icmpOutErrors"
    }
   ]
  },
  {
   "title": "ICMP Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 225 },
   "yaxes": [
    { "format": "short", "label": "messages out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_netstat_Icmp_InErrors{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "InErrors - Messages which the entity received but determined as having ICMP-specific errors (bad ICMP checksums, bad length, etc.)"
    }
   ]
  },
  {
   "title": "UDP In / Out",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 235 },
   "yaxes": [
    { "format": "short", "label": "datagrams out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_netstat_Udp_InDatagrams{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "InDatagrams - Datagrams received"
    },
    {
     "expr": "rate(node_netstat_Udp_OutDatagrams{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "OutDatagrams - Datagrams sent"
    }
   ]
  },
  {
   "title": "UDP Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 235 },
   "yaxes": [
    { "format": "short", "label": "datagrams" }
   ],
   "targets": [
    {
     "expr": "rate(node_netstat_Udp_InErrors{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "InErrors - UDP Datagrams that could not be delivered to an application"
    },
    {
     "expr": "rate(node_netstat_Udp_NoPorts{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "NoPorts - UDP Datagrams received on a port with no listener"
    },
    {
     "expr": "rate(node_netstat_UdpLite_InErrors{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "InErrors Lite - UDPLite Datagrams that could not be delivered to an application"
    },
    {
     "expr": "rate(node_netstat_Udp_RcvbufErrors{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "RcvbufErrors - UDP buffer errors received"
    },
    {
     "expr": "rate(node_netstat_Udp_SndbufErrors{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "SndbufErrors - UDP buffer errors send"
    }
   ]
  },
  {
   "title": "TCP In / Out",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 245 },
   "yaxes": [
    { "format": "short", "label": "datagrams out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_netstat_Tcp_InSegs{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "InSegs - Segments received, including those received in error. This count includes segments received on currently established connections"
    },
    {
     "expr": "rate(node_netstat_Tcp_OutSegs{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "OutSegs - Segments sent, including those on current connections but excluding those containing only retransmitted octets"
    }
   ]
  },
  {
   "title": "TCP Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 245 },
   "yaxes": [
    { "format": "short", "label": "counter" }
   ],
   "targets": [
    {
     "expr": "rate(node_netstat_TcpExt_ListenOverflows{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "ListenOverflows - Times the listen queue of a socket overflowed"
    },
    {
     "expr": "rate(node_netstat_TcpExt_ListenDrops{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "ListenDrops - SYNs to LISTEN sockets ignored"
    },
    {
     "expr": "rate(node_netstat_TcpExt_TCPSynRetrans{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "TCPSynRetrans - SYN-SYN/ACK retransmits to break down retransmissions in SYN, fast/timeout retransmits"
    },
    {
     "expr": "rate(node_netstat_Tcp_RetransSegs{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "RetransSegs - Segments retransmitted - that is, the number of TCP segments transmitted containing one or more previously transmitted octets"
    },
    {
     "expr": "rate(node_netstat_Tcp_InErrs{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "InErrs - Segments received in error (e.g., bad TCP checksums)"
    },
    {
     "expr": "rate(node_netstat_Tcp_OutRsts{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "OutRsts - Segments sent with RST flag"
    }
   ]
  },
  {
   "title": "TCP Connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 255 },
   "yaxes": [
    { "format": "short", "label": "connections" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "CurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT"
    },
    {
     "expr": "node_netstat_Tcp_MaxConn{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "MaxConn - Limit on the total number of TCP connections the entity can support (Dinamic is \"-1\")"
    }
   ]
  },
  {
   "title": "TCP SynCookie",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 255 },
   "yaxes": [
    { "format": "short", "label": "counter out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_netstat_TcpExt_SyncookiesFailed{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "SyncookiesFailed - Invalid SYN cookies received"
    },
    {
     "expr": "rate(node_netstat_TcpExt_SyncookiesRecv{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "SyncookiesRecv - SYN cookies received"
    },
    {
     "expr": "rate(node_netstat_TcpExt_SyncookiesSent{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "SyncookiesSent - SYN cookies sent"
    }
   ]
  },
  {
   "title": "TCP Direct Transition",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 265 },
   "yaxes": [
    { "format": "short", "label": "connections" }
   ],
   "targets": [
    {
     "expr": "rate(node_netstat_Tcp_ActiveOpens{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "ActiveOpens - TCP connections that have made a direct transition to the SYN-SENT state from the CLOSED state"
    },
    {
     "expr": "rate(node_netstat_Tcp_PassiveOpens{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "PassiveOpens - TCP connections that have made a direct transition to the SYN-RCVD state from the LISTEN state"
    }
   ]
  },
  { "title": "Node Exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 275 } },
  {
   "title": "Node Exporter Scrape Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 276 },
   "yaxes": [
    { "format": "s", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "node_scrape_collector_duration_seconds{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{collector}} - Scrape duration"
    }
   ]
  },
  {
   "title": "Node Exporter Scrape",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 276 },
   "yaxes": [
    { "format": "short", "label": "counter" }
   ],
   "targets": [
    {
     "expr": "node_scrape_collector_success{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{collector}} - Scrape success"
    },
    {
     "expr": "node_textfile_scrape_error{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{collector}} - Scrape textfile error (1 = true)"
    }
   ]
  }
 ]
}