{
 "title": "Nvidia SMI Metrcs",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "GPU Util", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "nvidia_smi_utilization_gpu_ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(nvidia_smi_utilization_gpu_ratio) by  (app_kubernetes_io_instance, instance)"
    }
   ]
  },
  {
   "title": "nvidia_smi_encoder_stats_session_count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "sum(nvidia_smi_encoder_stats_session_count) by  (app_kubernetes_io_instance, instance)"
    }
   ]
  },
  {
   "title": "nvidia_smi_encoder_stats_average_fps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "sum(nvidia_smi_encoder_stats_average_fps) by  (app_kubernetes_io_instance, instance)"
    }
   ]
  },
  { "title": "GPU Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "nvidia_smi_memory_used_bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(nvidia_smi_memory_used_bytes) by  (app_kubernetes_io_instance, instance)"
    }
   ]
  },
  {
   "title": "nvidia_smi_memory_free_bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(nvidia_smi_memory_free_bytes) by  (app_kubernetes_io_instance, instance)"
    }
   ]
  },
  {
   "title": "nvidia_smi_memory_total_bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 9 },
   "targets": [
    {
     "expr": "sum(nvidia_smi_memory_total_bytes) by  (app_kubernetes_io_instance, instance)"
    }
   ]
  },
  { "title": "GPU Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "nvidia_smi_temperature_gpu",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(nvidia_smi_temperature_gpu) by  (app_kubernetes_io_instance, instance)"
    }
   ]
  },
  {
   "title": "nvidia_smi_power_draw_watts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 17 },
   "targets": [
    {
     "expr": "sum(nvidia_smi_power_draw_watts) by  (app_kubernetes_io_instance, instance)"
    }
   ]
  },
  {
   "title": "nvidia_smi_pstate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 17 },
   "targets": [
    {
     "expr": "sum(nvidia_smi_pstate) by  (app_kubernetes_io_instance, instance)"
    }
   ]
  },
  { "title": "PCI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "nvidia_smi_pci_bus",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(nvidia_smi_pci_bus) by  (app_kubernetes_io_instance, instance)"
    }
   ]
  },
  {
   "title": "nvidia_smi_pcie_link_width_current",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 25 },
   "targets": [
    {
     "expr": "sum(nvidia_smi_pcie_link_width_current) by  (app_kubernetes_io_instance, instance)"
    }
   ]
  },
  {
   "title": "nvidia_smi_pci_device",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 25 },
   "targets": [
    {
     "expr": "sum(nvidia_smi_pci_device) by  (app_kubernetes_io_instance, instance)"
    }
   ]
  },
  {
   "title": "nvidia_smi_pcie_link_gen_current",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(nvidia_smi_pcie_link_gen_current) by  (app_kubernetes_io_instance, instance)"
    }
   ]
  },
  {
   "title": "nvidia_smi_pcie_link_width_max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 32 },
   "targets": [
    {
     "expr": "sum(nvidia_smi_pcie_link_width_max) by  (app_kubernetes_io_instance, instance)"
    }
   ]
  },
  {
   "title": "nvidia_smi_pcie_link_gen_max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 32 },
   "targets": [
    {
     "expr": "sum(nvidia_smi_pcie_link_gen_max) by  (app_kubernetes_io_instance, instance)"
    }
   ]
  },
  { "title": "Throttle", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "nvidia_smi_clocks_throttle_reasons_gpu_idle",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(nvidia_smi_clocks_throttle_reasons_gpu_idle) by  (app_kubernetes_io_instance, instance)"
    }
   ]
  },
  {
   "title": "nvidia_smi_clocks_throttle_reasons_active",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 40 },
   "targets": [
    {
     "expr": "sum(nvidia_smi_clocks_throttle_reasons_active) by  (app_kubernetes_io_instance, instance)"
    }
   ]
  },
  {
   "title": "nvidia_smi_clocks_throttle_reasons_applications_clocks_setting",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 40 },
   "targets": [
    {
     "expr": "sum(nvidia_smi_clocks_throttle_reasons_applications_clocks_setting) by  (app_kubernetes_io_instance, instance)"
    }
   ]
  },
  {
   "title": "nvidia_smi_clocks_throttle_reasons_supported",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sum(nvidia_smi_clocks_throttle_reasons_supported) by  (app_kubernetes_io_instance, instance)"
    }
   ]
  },
  {
   "title": "nvidia_smi_clocks_throttle_reasons_sync_boost",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 47 },
   "targets": [
    {
     "expr": "sum(nvidia_smi_clocks_throttle_reasons_sync_boost) by  (app_kubernetes_io_instance, instance)"
    }
   ]
  },
  {
   "title": "nvidia_smi_clocks_throttle_reasons_hw_thermal_slowdown",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 47 },
   "targets": [
    {
     "expr": "sum(nvidia_smi_clocks_throttle_reasons_hw_thermal_slowdown) by  (app_kubernetes_io_instance, instance)"
    }
   ]
  },
  {
   "title": "nvidia_smi_clocks_throttle_reasons_hw_slowdown",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "sum(nvidia_smi_clocks_throttle_reasons_hw_slowdown) by  (app_kubernetes_io_instance, instance)"
    }
   ]
  },
  {
   "title": "nvidia_smi_clocks_throttle_reasons_sw_thermal_slowdown",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 54 },
   "targets": [
    {
     "expr": "sum(nvidia_smi_clocks_throttle_reasons_sw_thermal_slowdown) by  (app_kubernetes_io_instance, instance)"
    }
   ]
  },
  {
   "title": "nvidia_smi_clocks_throttle_reasons_sw_power_cap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 54 },
   "targets": [
    {
     "expr": "sum(nvidia_smi_clocks_throttle_reasons_sw_power_cap) by  (app_kubernetes_io_instance, instance)"
    }
   ]
  },
  { "title": "Clocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "nvidia_smi_clocks_current_graphics_clock_hz",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "sum(nvidia_smi_clocks_current_graphics_clock_hz) by  (app_kubernetes_io_instance, instance)"
    }
   ]
  },
  {
   "title": "nvidia_smi_clocks_current_sm_clock_hz",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 62 },
   "targets": [
    {
     "expr": "sum(nvidia_smi_clocks_current_sm_clock_hz) by  (app_kubernetes_io_instance, instance)"
    }
   ]
  },
  {
   "title": "nvidia_smi_clocks_throttle_reasons_hw_power_brake_slowdown",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 62 },
   "targets": [
    {
     "expr": "sum(nvidia_smi_clocks_throttle_reasons_hw_power_brake_slowdown) by  (app_kubernetes_io_instance, instance)"
    }
   ]
  },
  {
   "title": "nvidia_smi_clocks_current_video_clock_hz",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "sum(nvidia_smi_clocks_current_video_clock_hz) by  (app_kubernetes_io_instance, instance)"
    }
   ]
  },
  {
   "title": "nvidia_smi_clocks_current_memory_clock_hz",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 69 },
   "targets": [
    {
     "expr": "sum(nvidia_smi_clocks_current_memory_clock_hz) by  (app_kubernetes_io_instance, instance)"
    }
   ]
  },
  {
   "title": "nvidia_smi_clocks_max_sm_clock_hz",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 69 },
   "targets": [
    {
     "expr": "sum(nvidia_smi_clocks_max_sm_clock_hz) by  (app_kubernetes_io_instance, instance)"
    }
   ]
  }
 ]
}