{
 "title": "Rsync status",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "resolution", "query": "30s,5m,1h" },
   { "name": "interval", "query": "4h" },
   {
    "name": "pvc",
    "query": {
     "query": "label_values(kubelet_volume_stats_used_bytes, persistentvolumeclaim)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Used: $pvc",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "repeat": "pvc",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (persistentvolumeclaim) (topk(1, (kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"$pvc\"})))",
     "legendFormat": "Capacity: {{persistentvolumeclaim}}"
    },
    {
     "expr": "sum by (persistentvolumeclaim)  (topk(1, kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"$pvc\"}))",
     "legendFormat": "Used : {{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Rsync cronJob Log",
   "type": "logs",
   "gridPos": { "h": 24, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "{namespace=\"media\", app=~\"rsync-.*\"}",
     "maxLines": 50
    }
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "graph",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(irate(container_network_receive_bytes_total{namespace=~\".+\"}[$interval:$resolution])) by (namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}