# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: plex-kube-plex-data
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 1Ti
# ---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plex-kube-plex-transcode
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: extradata-ocean
spec:
  storageClassName: nfs-ocean
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: extradata-ocean
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Ti
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data01/complete
    server: ocean
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sda1-node004
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Ti
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /sda1
    server: node004
    readOnly: false
