tautulli:
  env:
    TZ: America/Los_Angeles

  securityContext:
    runAsNonRoot: true
    runAsGroup: 1001
    runAsUser: 1001
    fsGroup: 1001

  ingress:
    main:
      enabled: true
      primary: true
      annotations:
        kubernetes.io/ingress.class: nginx
      labels: {}
      hosts:
        - host: tautulli.svc.cluster.local
          paths:
            - path: /
              pathType: Prefix
              service:
                # -- Overrides the service name reference for this path
                name: tautulli
                # -- Overrides the service port reference for this path
                port: 8181
      tls: []

  persistence:
    config:
      enabled: true
      existingClaim: tautulli-config
      mountPath: /config
    logs:
      enabled: true
      existingClaim: plex-config
      mountPath: /plex-config

