tautulli:
  env:
    TZ: America/Los_Angeles

  ingress:
    main:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      labels: {}
      hosts:
        - host: tautulli.svc.cluster.local
          paths:
            - path: /
              pathType: Prefix
      tls: []
    hostNetwork: false

  persistence:
    config:
      enabled: true
      mountPath: /config
      accessMode: ReadWriteMany
      storageClass: rook-cephfs
      size: 10Gi
