# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   namespace: media
#   name: ceph-mounts
#   labels:
#     app: ceph-mounts
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: ceph-mounts
#   template:
#     metadata:
#       labels:
#         app: ceph-mounts
#     spec:
#       dnsPolicy: ClusterFirstWithHostNet
#       containers:
#         - name: rsync-tdarr-config
#           image: instrumentisto/rsync-ssh
#           command:
#           - rsync
#           - -rav
#           - --stats
#           - --delete
#           - --chown=1000:1000
#           - /nfs-ocean/services/tdarr/
#           - /tdarr-config/
#           imagePullPolicy: IfNotPresent
#           tty: true
#           securityContext:
#             runAsNonRoot: false
#           volumeMounts:
#           - name: nfs-ocean
#             mountPath: /nfs-ocean
#           {{- range .Values.persistentVolumeClaims }}
#           - name: {{ .name}}
#             mountPath: /{{ .name}}
#           {{- end }}
#         - name: rsync-plex-config
#           image: instrumentisto/rsync-ssh
#           command:
#           - rsync
#           - -rav
#           - --stats
#           - --delete
#           - --chown=1000:1000
#           - /nfs-ocean/services/plex/config/
#           - /plex-config/
#           imagePullPolicy: IfNotPresent
#           tty: true
#           securityContext:
#             runAsNonRoot: false
#           volumeMounts:
#           - name: nfs-ocean
#             mountPath: /nfs-ocean
#           {{- range .Values.persistentVolumeClaims }}
#           - name: {{ .name }}
#             mountPath: /{{ .name }}
#           {{- end }}
#         - name: rsync-tv
#           image: instrumentisto/rsync-ssh
#           command:
#           - rsync
#           - -rav
#           - --stats
#           - --delete
#           - --chown=1000:1000
#           - /nfs-ocean/complete/tv/
#           - /tv
#           imagePullPolicy: IfNotPresent
#           tty: true
#           securityContext:
#             runAsNonRoot: false
#           volumeMounts:
#           - name: nfs-ocean
#             mountPath: /nfs-ocean
#           {{- range .Values.persistentVolumeClaims }}
#           - name: {{ .name }}
#             mountPath: /{{ .name }}
#           {{- end }}
#         - name: rsync-movies
#           image: instrumentisto/rsync-ssh
#           command:
#           - rsync
#           - -rav
#           - --stats
#           - --delete
#           - --chown=1000:1000
#           - /nfs-ocean/complete/movies/
#           - /movies
#           imagePullPolicy: IfNotPresent
#           tty: true
#           securityContext:
#             runAsNonRoot: false
#           volumeMounts:
#           - name: nfs-ocean
#             mountPath: /nfs-ocean
#           {{- range .Values.persistentVolumeClaims }}
#           - name: {{ .name }}
#             mountPath: /{{ .name }}
#           {{- end }}
#         - name: ubuntu
#           image: ubuntu:latest
#           command: ['sh', '-c', 'sleep 3600']
#           imagePullPolicy: IfNotPresent
#           tty: true
#           securityContext:
#             runAsNonRoot: false
#           volumeMounts:
#           - name: nfs-ocean
#             mountPath: /nfs-ocean
#           {{- range .Values.persistentVolumeClaims }}
#           - name: {{ .name }}
#             mountPath: /{{ .name }}
#           {{- end }}
#       volumes:
#       {{- range .Values.persistentVolumeClaims }}
#       - name: {{ .name}}
#         persistentVolumeClaim:
#           claimName: {{ .name }}
#           readOnly: false
#       {{- end }}
#       - name: nfs-ocean
#         persistentVolumeClaim:
#           claimName: nfs-ocean-pvc
#           readOnly: false
