apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-local
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100G
  volumeMode: Filesystem
  hostPath:
    path: "/tmp/transcode"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-local
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100G
  storageClassName: manual
  volumeName: plex-local