plex:
  # IMPORTANT NOTE
  #
  # This chart inherits from our common library chart. You can check the default values/options here:
  # https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
  #

  image:
    # -- image repository
    repository: ghcr.io/k8s-at-home/plex
    # -- image tag
    tag: v1.23.2.4656-85f0adf5b
    # -- image pull policy
    pullPolicy: IfNotPresent

  # -- environment variables. See [plex docs](https://support.plex.tv/articles/201105343-advanced-hidden-server-settings/) for more details.
  # **NOTE:** Plex preference options are camelCase and CASE SENSITIVE!
  # You can do horrible things to your Plex configuration if you are not careful
  # @default -- See below
  env:
    # -- Set the container timezone
    TZ: America/Los_Angeles
    ADVERTISE_IP: http://plex.svc.cluster.local
    # ALLOWED_NETWORKS:
    # PLEX_CLAIM: "6SWvgNykocyxaHJszdz5"
    FriendlyName: plex-kube
    # EnableIPv6: 0
    LogVerbose: 1
    logDebug: 1
    # PLEX_PREFERENCE_4: "DisableTLSv1_0=1"
    # PLEX_PREFERENCE_5: "LanNetworksBandwidth=xxx.xxx.xxx.0/18\,xxx.xxx.xxx.0/24\,xxx.xxx.xxx.0/24"
    # PLEX_PREFERENCE_6: "TranscoderQuality=2"
    # PLEX_PREFERENCE_7: "TreatWanIpAsLocal=0"
    # PLEX_PREFERENCE_8: "TranscoderH264BackgroundPreset=fast"

  # -- Configures service settings for the chart.
  # @default -- See values.yaml
  service:
    main:
      primary: true
      ports:
        http:
          port: 32400
    dnla-tcp:
      enabled: false
      type: NodePort
      ports:
        dnla-tcp:
          enabled: true
          port: 32469
          protocol: TCP
          targetPort: 32469
      externalTrafficPolicy: Local
    dnla-udp:
      enabled: false
      type: NodePort
      ports:
        dnla-udp:
          enabled: true
          port: 1900
          protocol: TCP
          targetPort: 1900
      externalTrafficPolicy: Local

  ingress:
    main:
      # -- Enable an ingress for the code-server add-on.
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        # kubernetes.io/tls-acme: "true"
      labels: {}
      hosts:
        - host: plex.svc.cluster.local
          paths:
            - path: /
              # Ignored if not kubeVersion >= 1.14-0
              pathType: Prefix
      tls: []
      #  - secretName: chart-example-tls
      #    hosts:
      #      - code.chart-example.local

  # -- Enable devices to be discoverable
  hostNetwork: false

  # affinity:
  #   podAntiAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #     - labelSelector:
  #         matchExpressions:
  #           - key: app.kubernetes.io/instance
  #             operator: In
  #             values:
  #             - plex
  #       topologyKey: kubernetes.io/hostname

  # -- Configure persistence settings for the chart under this key.
  # @default -- See values.yaml
  persistence:
    config:
      enabled: true
      mountPath: /config
      accessMode: ReadWriteMany
      storageClass: rook-cephfs
      size: 100Gi

    transcode:
      existingClaim: transcode
      enabled: true
      mountPath: /transcode

    tv:
      existingClaim: tv
      enabled: true
      mountPath: /tv

    movies:
      existingClaim: movies
      enabled: true
      mountPath: /movies

  # -- Configure the Security Context for the Pod
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    # # Hardware acceleration using an Intel iGPU w/ QuickSync
    # # These IDs below should be matched to your `video` and `render` group on the host
    # # To obtain those IDs run the following grep statement on the host:
    # # $ cat /etc/group | grep "video\|render"
    # # video:x:44:
    # # render:x:109:
    # supplementalGroups:
    # - 44
    # - 109

  # autoscaling:
  #   enabled: true
  #   target:  # deploymentname
  #   minReplicas:  1
  #   maxReplicas:  5
  #   targetCPUUtilizationPercentage:  90
    # targetMemoryUtilizationPercentage:  20

  # -- Configure the resource requests and/or limits for the Pod
  resources:
    requests:
    #   # Hardware acceleration using an Intel iGPU w/ QuickSync and
    #   # using intel-gpu-plugin (https://github.com/intel/intel-device-plugins-for-kubernetes)
    #   gpu.intel.com/i915: 1
      cpu: 16
      memory: 4Gi
    limits:
    #   # Hardware acceleration using an Intel iGPU w/ QuickSync and
    #   # using intel-gpu-plugin (https://github.com/intel/intel-device-plugins-for-kubernetes)
      cpu: 32
      memory: 32Gi