{{- with .Values.nfsVolumes }}
{{- range . }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: "rsync-{{ .pvc }}"
spec:
  #          ┌──────────────── minute (0 - 59)
  #          │ ┌───────────── hour (0 - 23)
  #          │ │ ┌───────────── day of the month (1 - 31)
  #          │ │ │ ┌───────────── month (1 - 12)
  #          │ │ │ │ ┌───────────── day of the week (0 - 6) (Sunday to Saturday;
  #          │ │ │ │ │                 7 is also Sunday on some systems)
  #          │ │ │ │ │
  #          │ │ │ │ │
  #          * * * * *
  schedule: "15 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: "rsync-{{ .pvc }}"
            image: instrumentisto/rsync-ssh
            imagePullPolicy: IfNotPresent
            command:
            - rsync
            - -rav
            - --stats
            - --delete
            - --chown=1000:1000
            - {{ .nfs }}/
            - {{ .ceph }}
            volumeMounts:
            - name: nfs-ocean
              mountPath: /nfs-ocean
            - name: {{ .pvc }}
              mountPath: {{ .ceph }}
          volumes:
          - name: nfs-ocean
            persistentVolumeClaim:
              claimName: nfs-ocean-pvc
              readOnly: true
          - name: {{ .pvc }}
            persistentVolumeClaim:
              claimName: {{ .pvc }}
              readOnly: false
          restartPolicy: OnFailure
{{- end }}
{{- end }}