nzbget:
  #
  # IMPORTANT NOTE
  #
  # This chart inherits from our common library chart. You can check the default values/options here:
  # https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
  #

  image:
    # -- image repository
    repository: ghcr.io/k8s-at-home/nzbget
    # -- image tag
    tag: latest
    # -- image pull policy
    pullPolicy: Always

  # -- Configures service settings for the chart.
  # @default -- See values.yaml
  service:
    main:
      ports:
        http:
          port: 6789

  ingress:
    # -- Enable and configure ingress settings for the chart under this key.
    # @default -- See values.yaml
    main:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: nzbget.svc.cluster.local
          paths:
            - path: /
              # Ignored if not kubeVersion >= 1.14-0
              pathType: Prefix

  # -- Configure persistence settings for the chart under this key.
  # @default -- See values.yaml
  persistence:
    config:
      enabled: true
      storageClass: rook-cephfs
      mountPath: /config

    incoming:
      enabled: true
      storageClass: rook-cephfs
      mountPath: /incoming
      accessMode: ReadWriteOnce
      size: 100G

    tv:
      existingClaim: tv
      enabled: true
      mountPath: /tv

    movies:
      existingClaim: movies
      enabled: true
      mountPath: /movies

  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
