nzbget:
  #
  # IMPORTANT NOTE
  #
  # This chart inherits from our common library chart. You can check the default values/options here:
  # https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
  #

  image:
    # -- image repository
    repository: ghcr.io/k8s-at-home/nzbget
    # -- image tag
    tag: latest
    # -- image pull policy
    pullPolicy: Always

  # -- Configures service settings for the chart.
  # @default -- See values.yaml
  service:
    main:
      ports:
        http:
          port: 6789

  ingress:
    # -- Enable and configure ingress settings for the chart under this key.
    # @default -- See values.yaml
    main:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: nzbget.svc.cluster.local
          paths:
            - path: /
              # Ignored if not kubeVersion >= 1.14-0
              pathType: Prefix

  # -- Configure persistence settings for the chart under this key.
  # @default -- See values.yaml
  persistence:
    config:
      enabled: true
      storageClass: nfs-node004
      mountPath: /config

    media:
      enabled: true
      mountPath: /media
      accessMode: ReadWriteMany
      storageClass: media-node004
      size: 1Gi

    downloads:
      enabled: false
      mountPath: /downloads
