# {{ $count := (.Values.pvcNodes | int) }}
# {{range $i, $e := until $count }}
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: data-consul-consul-consul-server-{{- $i }}
# spec:
#   accessModes:
#   - ReadWriteMany
#   resources:
#     requests:
#       storage: 10Gi
#   storageClassName: cephfs
# {{- end }}
