apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - all.yaml

patchesJson6902:
  - target:
      version: v1
      kind: CustomResourceDefinition
      name: prometheuses.monitoring.coreos.com
    patch: |-
      - op: delete
        path: /metadata/annotations/kubectl.kubernetes.io/last-applied-configuration
        value: kubectl.kubernetes.io/last-applied-configuration
