apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - all.yaml

patchesJson6902:
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: ".*"
    patch: |-
      - op: remove
        path: /metadata/annotations
        value: kubectl.kubernetes.io/last-applied-configuration
  - target:
      version: v1
      kind: ConfigMap
      name: ".*"
    patch: |-
      - op: add
        path: "/metadata/annotations~argocd.argoproj.io/sync-options"
        value: "Replace=true"