# Defaults
repoURL: &repoURL "https://github.com/bluefishforsale/homelab-kube.git"

# Sync policy
syncPolicy: &syncPolicy
  automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
    prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
    selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
    allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
  syncOptions:     # Sync options which modifies sync behavior
  - Validate=false # disables resource validation (equivalent to 'kubectl apply --validate=false') ( true by default ).
  - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
  - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
  - PruneLast=true # Allow the ability for resource pruning to happen as a final, implicit wave of a sync operation
  # The retry feature is available since v1.7
  retry:
    limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
    backoff:
      duration: 15s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
      factor: 2 # a factor to multiply the base duration after each failed retry
      maxDuration: 3m # the maximum amount of time allowed for the backoff strategy

  # Will ignore differences between live and desired states during the diff. Note that these configurations are not
  # used during the sync process.
ignoreDifferences: &ignoreDifferences
  # for the specified json pointers
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  # for the specified managedFields managers
  - group: "*"
    kind: "*"
    managedFieldsManagers:
    - kube-controller-manager

##############################################################################################################
# we loop this section per app chart
##############################################################################################################
Applications:

  - name: argo-tunnel
    path: charts/argo-tunnel
    namespace: cloudflare
    project: homelab
    repoURL: *repoURL
    syncPolicy: *syncPolicy
    ignoreDifferences: *ignoreDifferences

  - name: argo-cd
    path: charts/argo-cd
    namespace: argocd
    project: homelab
    repoURL: *repoURL
    syncPolicy: *syncPolicy
    ignoreDifferences: *ignoreDifferences

  - name: root-apps
    path: charts/argocd-applications
    namespace: argocd
    project: homelab
    repoURL: *repoURL
    syncPolicy: *syncPolicy
    ignoreDifferences: *ignoreDifferences

  ### do not enable until PV/PVC re-attach works
  # - name: ceph-filesystems
  #   path: charts/ceph-filesystems
  #   namespace: media
  #   project: homelab
  #   repoURL: *repoURL
  #   syncPolicy: *syncPolicy
  #   ignoreDifferences: *ignoreDifferences

  - name: metallb
    path: charts/metallb
    namespace: metallb
    project: homelab
    repoURL: *repoURL
    syncPolicy: *syncPolicy
    ignoreDifferences: *ignoreDifferences

  - name: ingress-nginx
    path: charts/ingress-nginx
    namespace: nginx
    project: homelab
    repoURL: *repoURL
    syncPolicy: *syncPolicy
    ignoreDifferences: *ignoreDifferences

  - name: kube-prometheus-stack
    path: charts/kube-prometheus-stack
    namespace: monitoring
    project: homelab
    repoURL: *repoURL
    syncPolicy: *syncPolicy
    ignoreDifferences: *ignoreDifferences

  - name: promtail
    path: charts/promtail
    namespace: monitoring
    project: homelab
    repoURL: *repoURL
    syncPolicy: *syncPolicy
    ignoreDifferences: *ignoreDifferences

  - name: loki
    path: charts/loki
    namespace: monitoring
    project: homelab
    repoURL: *repoURL
    syncPolicy: *syncPolicy
    ignoreDifferences: *ignoreDifferences

  - name: metrics-server
    path: charts/metrics-server
    namespace: kube-system
    project: homelab
    repoURL: *repoURL
    syncPolicy: *syncPolicy
    ignoreDifferences: *ignoreDifferences

  - name: nvidia-support
    path: charts/nvidia-support
    namespace: kube-system
    project: homelab
    repoURL: *repoURL
    syncPolicy: *syncPolicy
    ignoreDifferences: *ignoreDifferences

  - name: rsync-cron
    path: charts/rsync-cron
    namespace: media
    project: homelab
    repoURL: *repoURL
    syncPolicy: *syncPolicy
    ignoreDifferences: *ignoreDifferences

  - name: tautulli
    path: charts/tautulli
    namespace: media
    project: homelab
    repoURL: *repoURL
    syncPolicy: *syncPolicy
    ignoreDifferences: *ignoreDifferences

  - name: plex
    path: charts/plex
    namespace: media
    project: homelab
    repoURL: *repoURL
    syncPolicy: *syncPolicy
    ignoreDifferences: *ignoreDifferences

  - name: radarr
    path: charts/radarr
    namespace: media
    project: homelab
    repoURL: *repoURL
    syncPolicy: *syncPolicy
    ignoreDifferences: *ignoreDifferences

  - name: sonarr
    path: charts/sonarr
    namespace: media
    project: homelab
    repoURL: *repoURL
    syncPolicy: *syncPolicy
    ignoreDifferences: *ignoreDifferences

  # - name: nzbget
  #   enabled: false
  #   path: charts/nzbget
  #   namespace: media
  #   project: homelab
  #   repoURL: *repoURL
  #   syncPolicy: *syncPolicy
  #   ignoreDifferences: *ignoreDifferences

  # - name: lidarr
  #   path: charts/lidarr
  #   namespace: media
  #   project: homelab
  #   repoURL: *repoURL
  #   syncPolicy: *syncPolicy
  #   ignoreDifferences: *ignoreDifferences

  # - name: tdarr
  #   path: charts/tdarr
  #   namespace: media
  #   project: homelab
  #   repoURL: *repoURL
  #   syncPolicy: *syncPolicy
  #   ignoreDifferences: *ignoreDifferences

  - name: cert-manager
    path: charts/cert-manager
    namespace: cert-manager
    project: homelab
    repoURL: *repoURL
    syncPolicy: *syncPolicy
    ignoreDifferences: *ignoreDifferences

  - name: vault
    path: charts/vault
    namespace: vault
    project: homelab
    repoURL: *repoURL
    syncPolicy: *syncPolicy
    ignoreDifferences: *ignoreDifferences

  - name: consul
    path: charts/consul
    namespace: consul
    project: homelab
    repoURL: *repoURL
    syncPolicy: *syncPolicy
    ignoreDifferences: *ignoreDifferences

  - name: flux
    path: charts/flux
    namespace: flux
    project: homelab
    repoURL: *repoURL
    syncPolicy: *syncPolicy
    ignoreDifferences: *ignoreDifferences
