{{- with .Values.persistentVolumeClaims }}
{{- range . }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
  {{- if .namespace }}
  namespace: {{ .namespace }}
  {{- end }}
spec:
  accessModes:
  - {{ .accessMode | default "ReadWriteMany" | trim | quote }}
  resources:
    requests:
      storage: {{ .storage }}
  storageClassName: {{ .storageClassName | default "rook-cephfs" | trim | quote }}
{{- end }}
{{- end }}
