apiVersion: v2
name: nvidia-support
version: 1.0.0

dependencies:
  # - name: nvidia-device-plugin
  #   version: 0.11.0
  #   repository: https://nvidia.github.io/k8s-device-plugin

  - name: nvidia-gpu-exporter
    version: 0.3.1
    repository: https://utkuozdemir.org/helm-charts

  # bare-metal w/ nvidia drivers + toolkit installed
  # https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/getting-started.html#bare-metal-passthrough-with-pre-installed-drivers-and-nvidia-container-toolkit
  - name: gpu-operator
    version: 1.11.0
    repository: https://helm.ngc.nvidia.com/nvidia