apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - all.yaml

patchesStrategicMerge:
- |-
  apiVersion: apiextensions.k8s.io/v1
  kind: CustomResourceDefinition
  metadata:
    annotations:
      argocd.argoproj.io/sync-options: Replace=true
    name: ".*"
  apiVersion: v1
  kind: ConfigMap
  metadata:
    annotations:
      argocd.argoproj.io/sync-options: Replace=true
    name: ".*"

patches:
- patch: |-
    - op: replace
      path: /apiVersion
      value: autoscaling/v2beta2
    target:
      group: autoscaling
      version: v2
      kind: HorizontalPodAutoscaler