tdarr:
  #
  # IMPORTANT NOTE
  #
  # This chart inherits from our common library chart. You can check the default values/options here:
  # https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
  #

  image:
    # -- image repository
    repository: haveagitgat/tdarr
    # -- image tag
    tag: latest
    # -- image pull policy
    pullPolicy: IfNotPresent

  # -- environment variables.
  # @default -- See below
  env:
    # -- Set the container timezone
    TZ: America/Los_Angeles

  # -- Configures service settings for the chart.
  # @default -- See values.yaml
  service:
    main:
      ports:
        http:
          port: 8265
        server:
          enabled: true
          protocol: TCP
          port: 8266

  ingress:
    # -- Enable and configure ingress settings for the chart under this key.
    # @default -- See values.yaml
    main:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: tdarr.svc.cluster.local
          paths:
            - path: /
              # Ignored if not kubeVersion >= 1.14-0
              pathType: Prefix

  node:
    # -- Deploy a tdarr node.
    enabled: true
    # -- Node ID
    id: node
    image:
      # -- image repository
      repository: haveagitgat/tdarr_node
      # -- image tag
      tag: latest
      # -- image pull policy
      pullPolicy: IfNotPresent

 # @default -- See values.yaml
  persistence:
    config:
      enabled: true
      storageClass: nfs-node000
      accessMode: ReadWriteMany
      mountPath: /config
      size: 1G

    media:
      enabled: true
      mountPath: /media
      accessMode: ReadWriteMany
      storageClass: media-node004
      size: 1G

  # podSecurityContext:
  #   runAsUser: 1000
  #   runAsGroup: 1000
  #   fsGroup: 1000

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "kubernetes.io/hostname"
            operator: In
            values:
            - "node000"