apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - all.yaml

patchesStrategicMerge:
- |-
  apiVersion: isindir.github.com/v1alpha3
  kind: SopsSecret
  metadata:
    annotations:
      argocd.argoproj.io/sync-options: Replace=true
    name: ".*"
