kind: ConfigMap
apiVersion: v1
metadata:
  name: rook-config-override
  namespace: rook-ceph # namespace:cluster
data:
  config: |
    [global]
    osd_pool_default_size = 2
    mon_warn_on_pool_no_redundancy = true
    bdev_flock_retry = 20
    bluefs_buffered_io = false