# Note: one SopsSecret/secretTemplates per namesapce needed
# kube secrets expect to be base64, so echo "your-secret" | base64 before inclusion here
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: media-secrets
    namespace: media
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:PXThMbfS1geCGg==,iv:4XgI7c9jO3mXTzXJgGZ9T+iDaKJYr4ntWwyRdOS9MUU=,tag:tzH8nhHsUXSnv2jERS6cyw==,type:str]
          labels:
            app-name: ENC[AES256_GCM,data:VTmCLA==,iv:luoGO4rlmTmymkehWV7Il2/pac05vxadu7tJeI1B+7k=,tag:lXTgtnwymOkmvmuwatmv2Q==,type:str]
          data:
            plex-claim: ENC[AES256_GCM,data:ARMb4DUyGQZzb8Zo5nsstvKOWu2YGlZXZcMmkA==,iv:pMVVhFdfdq930uycDl+PsojiZmjcC/s6oRL3cOmeMrA=,tag:8rXFn4RVgMfzONQnLknR6w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-06-14T21:46:08Z"
    mac: ENC[AES256_GCM,data:kBzX1dlso7vFjHdiamc679c1YqeJI/Wq0uS3Vw9VcUEZ09kW0GYncUWFpmrbAneWGen6DNxBp2fVqgEp/KJw7WC9/6oUHzenSWtXrIoDBO3fzEjTA7rcfOkdeSvInImZNKUfusNz4kXowpFnZIhJXmFxi+PpKKDGyHIwvpYXY18=,iv:8ilyP9KEeBsRk4vxb9WXO6duTgeqasRb1zJaJJ5FuUE=,tag:9A6bGlhXRKrxi5ULlC3dkA==,type:str]
    pgp:
        - created_at: "2022-06-14T21:46:07Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA2JtKtHLNadqAQv9E9pgcSHp3PDM5sDAHV5iR0SY7vn4ZKGJZxLDlpCgHIKF
            GM7dOPZxg4doFEAP3pEIm9o3zPzkNis5NLEbRPjGqVyeo85ZzEgXmgE86HOPXYn1
            DeSHe7L6cCvoH70hncJnPHp7Bs3nr3WGlefolHnCfRn+UeBjJGkDIX0DFEwIOTw9
            djv1jKXaF+yALQ5CYDfUrprjvvnC6VtEKeWYjOq6uyWIjMropYcVFX1zbau1STGu
            CQzYyG8qDKLj5S6cURxM7IVGjLq6lYLBlMpZ5P5fq9+4SGLjywat6XZaYNOJATOw
            2COHuYHlhSRJpdEKXtcXlSPD9RBWExjRVHt+fI92H3W4qlDhysuP2q29+vMxLXLz
            HK2uXK/gGdjg36hZUhsoiuh1pK0Pc0fajUq+iXH7KR5+zNR6ndiChifUR20ArJTv
            I9FiwANPZF31dJtCOiNaIAh0L9GkvdhY2s3kKvNQqArSHU33fojv6QLjlgzoJvzF
            FVePR9UFcfokGG8FWtAM0l4Bfzp6ifaGXsgykjjkVRxC9NzonPOyq4vtYzDVF9/O
            pIB1QJ/3aoFAgtDBDN9+su7A+C+kAU7o0SS7miYOjzqNxzkDn5DYQqgnwgwS1tm8
            AGxGzRCycF2m6TMdmtdz
            =EpJH
            -----END PGP MESSAGE-----
          fp: DB012CF1A60704F5EBE42E1A5CD3A14C18B2F64A
    encrypted_suffix: Templates
    version: 3.7.3
---
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-06-14T21:46:08Z"
    mac: ENC[AES256_GCM,data:kBzX1dlso7vFjHdiamc679c1YqeJI/Wq0uS3Vw9VcUEZ09kW0GYncUWFpmrbAneWGen6DNxBp2fVqgEp/KJw7WC9/6oUHzenSWtXrIoDBO3fzEjTA7rcfOkdeSvInImZNKUfusNz4kXowpFnZIhJXmFxi+PpKKDGyHIwvpYXY18=,iv:8ilyP9KEeBsRk4vxb9WXO6duTgeqasRb1zJaJJ5FuUE=,tag:9A6bGlhXRKrxi5ULlC3dkA==,type:str]
    pgp:
        - created_at: "2022-06-14T21:46:07Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA2JtKtHLNadqAQv9E9pgcSHp3PDM5sDAHV5iR0SY7vn4ZKGJZxLDlpCgHIKF
            GM7dOPZxg4doFEAP3pEIm9o3zPzkNis5NLEbRPjGqVyeo85ZzEgXmgE86HOPXYn1
            DeSHe7L6cCvoH70hncJnPHp7Bs3nr3WGlefolHnCfRn+UeBjJGkDIX0DFEwIOTw9
            djv1jKXaF+yALQ5CYDfUrprjvvnC6VtEKeWYjOq6uyWIjMropYcVFX1zbau1STGu
            CQzYyG8qDKLj5S6cURxM7IVGjLq6lYLBlMpZ5P5fq9+4SGLjywat6XZaYNOJATOw
            2COHuYHlhSRJpdEKXtcXlSPD9RBWExjRVHt+fI92H3W4qlDhysuP2q29+vMxLXLz
            HK2uXK/gGdjg36hZUhsoiuh1pK0Pc0fajUq+iXH7KR5+zNR6ndiChifUR20ArJTv
            I9FiwANPZF31dJtCOiNaIAh0L9GkvdhY2s3kKvNQqArSHU33fojv6QLjlgzoJvzF
            FVePR9UFcfokGG8FWtAM0l4Bfzp6ifaGXsgykjjkVRxC9NzonPOyq4vtYzDVF9/O
            pIB1QJ/3aoFAgtDBDN9+su7A+C+kAU7o0SS7miYOjzqNxzkDn5DYQqgnwgwS1tm8
            AGxGzRCycF2m6TMdmtdz
            =EpJH
            -----END PGP MESSAGE-----
          fp: DB012CF1A60704F5EBE42E1A5CD3A14C18B2F64A
    encrypted_suffix: Templates
    version: 3.7.3
