persistentVolumeClaims:
  - name: tautulli-config
    namespace: media
    storage: 10Gi
    accessMode: ReadWriteMany
  - name: tdarr-config
    namespace: media
    storage: 1Gi
    accessMode: ReadWriteMany
  - name: sonarr-config
    namespace: media
    storage: 1Gi
    accessMode: ReadWriteMany
  - name: radarr-config
    namespace: media
    storage: 5Gi
    accessMode: ReadWriteMany
    storageClassName: rook-cephfs
  - name: plex-config
    namespace: media
    storage: 100Gi
    accessMode: ReadWriteMany
    storageClassName: rook-cephfs
  - name: transcode
    namespace: media
    storage: 1500M
    accessMode: ReadWriteMany
    storageClassName: rook-cephfs
  - name: tv
    namespace: media
    storage: 15T
    accessMode: ReadWriteMany
    storageClassName: rook-cephfs
  - name: movies
    namespace: media
    storage: 15T
    accessMode: ReadWriteMany
    storageClassName: rook-cephfs
  - name: music
    namespace: media
    storage: 1T
    accessMode: ReadWriteMany
    storageClassName: rook-cephfs
